### PR TITLE
fix: crash when output directory doesn't exist

### PR DESCRIPTION
**Pull request by HarikrishnanBalagopal**
### Was the PR tested

- [ ] I have added >=1 unit test(s) for every new method I have added.
- [ ] I have ensured all unit tests pass

### CODE REVIEW

**Comment by anhuong** [comment]
@HarikrishnanBalagopal You created two PRs with slightly different changes, should we look at this PR or PR #364 ? One references `model_args.output_dir` while the other references `training_args.output_dir`

**Comment by anhuong** [comment]
Also if you have done any testing with multi-GPU, please let us know as unit tests are running on CPU

**Comment by kmehant** [comment]
@anhuong Please review https://github.com/foundation-model-stack/fms-hf-tuning/pull/364 Thank you.

**Comment by HarikrishnanBalagopal** [comment]
> @HarikrishnanBalagopal You created two PRs with slightly different changes, should we look at this PR or PR #364 ? One references `model_args.output_dir` while the other references `training_args.output_dir`

This is the change required for the `wca` branch. PTAL at #364 for the required change in the `main` branch.

**Comment by HarikrishnanBalagopal** [comment]
> Also if you have done any testing with multi-GPU, please let us know as unit tests are running on CPU

Yes I have tested the same command with 1, 4 and 8 GPUs multiple times to ensure that the race condition doesn't occur.

**Pull request closed without merging**
