### PR TITLE
fix: remove fire ported from Hari's PR #303

### PR DESCRIPTION
**Pull request by HarikrishnanBalagopal**
### Description of the change

Remove the 2nd CLI parser (fire) because it's not necessary and throws errors when training with LoRA.

### Related issue number

Fixes https://github.com/foundation-model-stack/fms-hf-tuning/issues/47

### How to verify the PR

`make test`

### Was the PR tested

- [x] I have added >=1 unit test(s) for every new method I have added.
- [x] I have ensured all unit tests pass

### CODE REVIEW

**Comment by HarikrishnanBalagopal** [comment]
The errors are completely unrelated to the changes in the PR.

https://github.com/foundation-model-stack/fms-hf-tuning/actions/runs/10637170607/job/29490507719?pr=324#step:4:1329

```
E               ValueError: You passed `packing=False` to the SFTTrainer/SFTConfig, but you didn't pass a `dataset_text_field` or `formatting_func` argument.
```

Seems to be coming from

https://github.com/foundation-model-stack/fms-hf-tuning/blob/6cfb2ffdc2b1a47656ebbcc9d8d35e6df228151c/tests/test_sft_trainer.py#L509-L520

https://github.com/huggingface/trl/blob/d57e4b726561e5ae58fdc335f34029052944a4a3/trl/trainer/sft_trainer.py#L351

**Review by willmj — APPROVED** [review]
LGTM!

**Comment by ashokponkumar** [comment]
@anhuong can we merge this when you are comfortable with it?

**Comment by anhuong** [comment]
@HarikrishnanBalagopal what testing did you do for this change? We would want to ensure that with this change users can still run training from CLI, with JSON config, and from importing python module. Unit tests cover the python module and JSON config use cases. Thus if you test the CLI piece, then this should be sufficient

**Comment by willmj** [comment]
Implementing these changes on my machine:

Running LoRA:
```
% python tuning/sft_trainer.py \
--model_name_or_path Maykeye/TinyLLama-v0 \
--training_data_path tests/data/twitter_complaints_small.json \
--output_dir outputs/lora-tuning \
--num_train_epochs 5 \
--per_device_train_batch_size 4 \
--gradient_accumulation_steps 4 \
--learning_rate 1e-5 \
--response_template "\n### Label:" \
--dataset_text_field "output" \
--use_flash_attn false \
--torch_dtype "float32" \
--peft_method "lora" \
--r 8 \
--lora_dropout 0.05 \
--lora_alpha 16  \
--target_modules "v_proj" "c_proj"
```

Log:
```
{'loss': 7.9407, 'grad_norm': 4.002565860748291, 'learning_rate': 8.000000000000001e-06, 'epoch': 1.0}
 20%|█████████                                    | 1/5 [00:00<00:02,  1.74it/s]
{'loss': 3.9542, 'grad_norm': 2.8579704761505127, 'learning_rate': 4.000000000000001e-06, 'epoch': 2.0}
 60%|███████████████████████████                  | 3/5 [00:01<00:00,  3.46it/s]
 80%|████████████████████████████████████         | 4/5 [00:01<00:00,  2.96it/s]
{'loss': 3.8709, 'grad_norm': 1.6323113441467285, 'learning_rate': 0.0, 'epoch': 3.0}
100%|█████████████████████████████████████████████| 5/5 [00:01<00:00,  2.96it/s]
{'train_runtime': 1.7348, 'train_samples_per_second': 28.822, 'train_steps_per_second': 2.882, 'train_loss': 4.7181743621826175, 'epoch': 3.0}
100%|█████████████████████████████████████████████| 5/5 [00:01<00:00,  2.88it/s]
```

Fine Tuning
```
% python tuning/sft_trainer.py \
--model_name_or_path Maykeye/TinyLLama-v0 \
--training_data_path tests/data/twitter_complaints_small.jsonl \
--output_dir outputs/full-tuning \
--num_train_epochs 5 \
--per_device_train_batch_size 4 \
--gradient_accumulation_steps 4 \
--learning_rate 1e-5 \
--response_template "\n### Label:" \
--dataset_text_field "output" \
--use_flash_attn false \
--torch_dtype "float32"
```

Log:
```
{'loss': 7.9407, 'grad_norm': 23.814661026000977, 'learning_rate': 8.000000000000001e-06, 'epoch': 1.0}
{'loss': 3.8985, 'grad_norm': 17.079011917114258, 'learning_rate': 4.000000000000001e-06, 'epoch': 2.0}
{'loss': 3.7799, 'grad_norm': 9.279784202575684, 'learning_rate': 0.0, 'epoch': 3.0}
{'train_runtime': 1.6872, 'train_samples_per_second': 29.635, 'train_steps_per_second': 2.963, 'train_loss': 4.659521102905273, 'epoch': 3.0}
100%|█████████████████████████████████████████████| 5/5 [00:01<00:00,  2.96it/s]
```

**Review by anhuong — APPROVED** [review]

**Pull request merged**
